server:
  port: 9100

spring:
  application:
    name: explorer-zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    prefer-ip-address: true

zuul:
  host:
    max-total-connections: 500
  routes:
    api-run-image:
      path: /api/run/**
      serviceId: explorer-run-liver
      serviceUrl: http://localhost:9001/api/run/**
#      strip-prefix: false
#  prefix: /v1