server:
  port: 3306

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver

    #---  服务器url  ---#
    url: jdbc:mysql://10.13.81.186:3306/friendlyarm?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&useSSL=false&allowMultiQueries=true
    username: root
    password: lab205

    #---  zj 本机url  ---#
#    url: jdbc:mysql://localhost:3306/friendlyarm?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
#    username: one way one year
#    password: 123

    #---  T4 url  ---#
#    url: jdbc:mysql://127.0.0.1:3306/friendlyarm?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
#    username: root
#    password: 12345678

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: zju.edu.friendlyarm.pojo