server:
  port: 9001

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.13.81.186:3306/friendlyarm?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&useSSL=false&allowMultiQueries=true
    username: root
    password: lab205

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: zju.edu.friendlyarm.pojo