server:
  port: 9002


uploader:
  copy-images-to: \\10.13.81.186\TempImg
  cron-expression: 0 0 1 * * ?

spring:
  application:
    name: explorer-cloud

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    prefer-ip-address: true